name = "runaro"
compatibility_date = "2024-09-03"

# Environment variables
[vars]
NODE_ENV = "production"
VITE_SUPABASE_URL = "https://ojjpslrhyutizwpvvngu.supabase.co"
VITE_SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9qanBzbHJoeXV0aXp3cHZ2bmd1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyMzAyNDUsImV4cCI6MjA3MTgwNjI0NX0.qsKY1YPBaphie0BwV71-kHcg73ZfKNuBUHR9yHO78zA"
VITE_SITE_URL = "https://runaro.dk"

# Add missing pages configuration
[build]
pages_build_output_dir = "dist"