name = "runaro-game-finish-cron"
main = "game-finish-cron-refactored.js"
compatibility_date = "2024-09-03"

# Cron trigger - runs every 5 minutes
[triggers]
crons = ["*/5 * * * *"]

# Environment variables
[vars]
SUPABASE_URL = "https://ojjpslrhyutizwpvvngu.supabase.co"

# Secrets are provided via Wrangler Secrets, do NOT commit here:
#   wrangler secret put CRON_SECRET
