name = "runaro"
compatibility_date = "2024-09-03"

# Environment variables
[vars]
NODE_ENV = "production"
# TODO: Sæt disse i Cloudflare Pages miljø-variabler (Dashboard) i stedet for at committe værdier her.
VITE_SUPABASE_URL = "<set-in-pages-env>"
VITE_SUPABASE_PUBLISHABLE_KEY = "<set-in-pages-env>"
VITE_STRIPE_PUBLISHABLE_KEY = "<set-in-pages-env>"
VITE_SITE_URL = "https://runaro.dk"

# Add missing pages configuration
[build]
pages_build_output_dir = "dist"

# Note: Cron triggers belong to Cloudflare Workers, not Pages.
# Keep cron configuration only under workers/wrangler.toml
